version: '3.3'

services:
  client:
    build:
      context: ./client/
      dockerfile: ./Dockerfile
    ports:
      - "8002:8002"

  server:
    env_file:
      - server/.env
    build:
      context: ./server/
      dockerfile: ./Dockerfile
    ports:
      - "8001:8001"